// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aalug/go-gin-job-search/internal/worker (interfaces: TaskDistributor)

// Package mockworker is a generated GoMock package.
package mockworker

import (
	context "context"
	reflect "reflect"

	worker "github.com/aalug/job-finder-go/internal/worker"
	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskSendConfirmationEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendConfirmationEmail(arg0 context.Context, arg1 *worker.PayloadSendConfirmationEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendConfirmationEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendConfirmationEmail indicates an expected call of DistributeTaskSendConfirmationEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendConfirmationEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendConfirmationEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendConfirmationEmail), varargs...)
}

// DistributeTaskSendVerificationEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendVerificationEmail(arg0 context.Context, arg1 *worker.PayloadSendVerificationEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendVerificationEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendVerificationEmail indicates an expected call of DistributeTaskSendVerificationEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendVerificationEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendVerificationEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendVerificationEmail), varargs...)
}
