// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	DeleteCompany(ctx context.Context, id int32) error
	DeleteJob(ctx context.Context, id int32) error
	GetCompanyByID(ctx context.Context, id int32) (Company, error)
	GetCompanyByName(ctx context.Context, name string) (Company, error)
	GetJob(ctx context.Context, id int32) (Job, error)
	ListJobsByCompanyExactName(ctx context.Context, arg ListJobsByCompanyExactNameParams) ([]Job, error)
	ListJobsByCompanyID(ctx context.Context, arg ListJobsByCompanyIDParams) ([]Job, error)
	ListJobsByCompanyName(ctx context.Context, arg ListJobsByCompanyNameParams) ([]Job, error)
	ListJobsByIndustry(ctx context.Context, arg ListJobsByIndustryParams) ([]Job, error)
	ListJobsByLocation(ctx context.Context, arg ListJobsByLocationParams) ([]Job, error)
	ListJobsBySalaryRange(ctx context.Context, arg ListJobsBySalaryRangeParams) ([]Job, error)
	ListJobsByTitle(ctx context.Context, arg ListJobsByTitleParams) ([]Job, error)
	ListJobsMatchingUserSkills(ctx context.Context, arg ListJobsMatchingUserSkillsParams) ([]Job, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
